jobs:
  datagen:
    defaults:
      run:
        working-directory: main-repo
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: main-repo
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: manual-data
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref_name, '1.')}}
      name: Set up manual data repo
      run: 'cd ../manual-data

        MANUAL_BRANCH=manual-data/$(git branch --show-current)

        echo Online manual data branch: $MANUAL_BRANCH

        git fetch

        git switch $MANUAL_BRANCH || git switch --orphan $MANUAL_BRANCH

        cd ../main-repo

        '
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          build/fg_cache

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Create list of existing generated resources
      run: find src/generated/resources/ ! -path "**/.cache*" > resources.txt
    - continue-on-error: true
      name: Run data generation
      run: xvfb-run --auto-servernum bash -c "ie_manual_datagen_path=$(pwd)/../manual-data
        ./gradlew runData"
    - continue-on-error: true
      name: Check that no files have changed
      run: git update-index --really-refresh || (git diff && false)
    - continue-on-error: true
      name: Create list of actual generated resources
      run: find src/generated/resources/ ! -path "**/.cache*" > resources_new.txt
    - continue-on-error: true
      name: Check that no new resources have been created
      run: diff resources.txt resources_new.txt
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref_name, '1.')}}
      name: Commit and push manual data
      run: "cd ../manual-data/\ngit add --all\nif ! git diff-index --quiet HEAD ;\
        \ then\n  git config user.name github-actions\n  git config user.email github-actions@github.com\n\
        \  git commit -m \"Update generated manual data\"\n  git push --set-upstream\
        \ origin $(git branch --show-current)\nfi\n"
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          build/fg_cache

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Compile IE
      run: ./gradlew compileJava
    - continue-on-error: true
      name: Run unit tests
      run: ./gradlew test
    - continue-on-error: true
      name: Update APT cached
      run: sudo apt update
    - continue-on-error: true
      name: Install ffprobe
      run: sudo apt install ffmpeg
    - continue-on-error: true
      name: Check for stereo sound files
      run: scripts/check_sounds.sh
name: Check that generated data is up to date and update data for web manual
on:
  repository_dispatch:
    types: trigger-ga___test.yaml
